### PR TITLE
Replace execSync with exec and make convertTo async

### PR DESCRIPTION
**Pull request by nbarnett**
We have been running into issues with the Node.js event loop being blocked as a result of the `execSync` calls. This results in our lambda functions timing out before they can execute their cleanup code. 

The changes in this PR replace instances of `execSync` with `exec` (wrapped in a promise), so that the event loop isn't blocked. I have also bumped the version of `del` to v7.0.0 since that version contains the `deleteAsync` function.

### CODE REVIEW

**Comment by vladgolubev** [comment]
Thanks! Will `del@7.0.0` work in Node 16? I think it was converted to ESM module

**Comment by nbarnett** [comment]
Ah good point, I didn't realize it had been converted to ESM. I can revert the `del` upgrade and leave it as it. I think the other changes should still help with the issues that I'm having.

**Comment by nbarnett** [comment]
@vladgolubev I've updated the PR to exclude the changes to `del`. Let me know what you think.

**Review by vladgolubev — APPROVED** [review]

**Comment by vladgolubev** [comment]
@nbarnett I see that `del` can be invoked directly w/o `.sync()` method which will use promises. No need to upgrade. I will make the changes after I merge your PR.

**Comment by vladgolubev** [comment]
Published in https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v6.0.0

**Pull request merged**
